### ISSUE TITLE
Passing json data of POI to WikitudeView 

### ISSUE THREAD

**Issue by NamithaRavy** [joaquinlom/react-native-wikitude-sdk-example#13]
Hi,

I would like to know how to pass json data from the wikitudeComponent.js to the loadPoisFromJsonData() written inside the assets. I am a bit confused here could you please help me out.

**Comment by joaquinlom** [comment]
To send data from React Native to Wikitude component you need to call callJS and send a string. And viceversa you need to call inside the .js sendJSONObject and listen to the event in RN

**Comment by NamithaRavy** [comment]
Hey thanks for the quick help,  does callJS inject that received json to loadPoisFromJsonData()

**Comment by joaquinlom** [comment]
You will need to pass a string, that string is going to eval inside in the html/js assets experience. so if in your experience you have a method loadPOIFromJson(json) then you need to create a string with the data.

callJS('loadPOIFromJson('+data+')');

**Comment by NamithaRavy** [comment]
Thank you.. it worked!!

**Comment by NamithaRavy** [comment]
Thank you.. it worked!!
