### ISSUE TITLE
com.wikitudeexample.MainActiviy cannot be cast to com.reactnavigation.NavigationAcivity

### ISSUE THREAD

**Issue by alessapac** [joaquinlom/react-native-wikitude-sdk-example#4]
Hello,

after cloning he project (git clone https://github.com/joaquinlom/react-native-wikitude-sdk.git) and installing (npm install) I get the error after build process (build is successfull). Attaching screenshot below.

https://ibb.co/ssMDG27

Please help.

Thanks,
Best regards

**Comment by veryprofessionaldodo** [comment]
Same here. I'm testing Wikitude for work, but I'm having quite a bit of difficulty in setting things up, so I this demo would be quite useful.

**Comment by joaquinlom** [comment]
Hi. 
Yes this issue is more related that the demo is using React Native Navigation ,and in my experience is only happening on Debug (you can dismiss the error). I'm using right now (https://github.com/wix/react-native-navigation) for navigation with no problems.

**Comment by joaquinlom** [comment]
> Same here. I'm testing Wikitude for work, but I'm having quite a bit of difficulty in setting things up, so I this demo would be quite useful.

You can create a new issue with your problems and let's see what we can do :)

**Comment by veryprofessionaldodo** [comment]
Yeah, I don't think that will be necessary any longer, as you were right, just dismissing the error sufficed, and the application worked as expected! But thanks for your support :)
