### ISSUE TITLE
share button does not work

### ISSUE THREAD

**Issue by GianlucaP99** [joaquinlom/react-native-wikitude-sdk-example#8]
Hi,
I tried the sharing feature, but it doesn't seem to work. The first time it is clicked instead of obtaining the image, a very long string is obtained, if you decide not to share at the next attempt it does not work directly. I personally opted to take the screenshot directly from react in this way:

-------------------------------------------------------------------------------------------

const [savedImagePath, setSavedImagePath] = useState('');

useEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Icon name="camera" size={40} onPress={() => takeScreenShotAndShare()} />
      ),
    });
    
  }, [navigation]);

const takeScreenShotAndShare = () => {
    // To capture Screenshot
    captureScreen({
      // Either png or jpg (or webm Android Only), Defaults: png
      format: 'jpg',
      // Quality 0.0 - 1.0 (only available for jpg)
      quality: 0.8, 
    }).then(
      //callback function to get the result URL of the screnshot
      (uri) => {
        setSavedImagePath(uri);
      },
      (error) => console.error('Oops, Something Went Wrong', error),
    );    
  };

useEffect(() => {
    if (savedImagePath != '') {
      console.log('share image url: ', savedImagePath);
      onShare();
    }    
  }, [savedImagePath]);

const onShare = async () => {
    console.log("Image path!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
    console.log(savedImagePath);
    await Share.open({
      message: 'Share messaghe picture',
      title: 'share title',
      url: savedImagePath,
    })
      .then(res => {
        console.log(res);
      })
      .catch(err => {
        err && console.log(err);
      });
  };

-------------------------------------------------------------------------------------------

The problem is that the image of the wikitude component is not displayed (all black). I think this is the reason why we had opted to take the screenshot differently.

**Comment by joaquinlom** [comment]
Hi, please refer to the library itself not the example.
the share action, will be request an screenshot, and in the event will return a image as Base64, this image, you will need to share or save it as you want it.

**Comment by GianlucaP99** [comment]
yes perfect everything solved, thank you very much.
